### ISSUE TITLE
Convert our repo to be a rust workspace

### ISSUE THREAD

**Issue by astoycos** [kubernetes-sigs/blixt#218]
A [rust workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) will allow all our rust modules/crates to have dependency management and versioning from a central point while still coe-exising with our go processes. 

Again this is [what we do in bpfman](https://github.com/bpfman/bpfman/blob/main/Cargo.toml) so that can be a good reference

**Comment by shaneutt** [comment]
Makes perfect sense since we're moving to all Rust soon. :+1:

**Comment by astoycos** [comment]
@EandrewJones no rush at all but if you want to keep helping this is a logical good next issue :)

**Comment by EandrewJones** [comment]
> @EandrewJones no rush at all but if you want to keep helping this is a logical good next issue :)

I can pick this up. I started work on #50 already, but I can bracket that for now.

**Comment by astoycos** [comment]
/assign @EandrewJones  

Yeag I think #50 isn't as important, we can discuss further priorities during our meeting
