### ISSUE TITLE
Create performance tooling for the Bpf Dataplane

### ISSUE THREAD

**Issue by astoycos** [kubernetes-sigs/blixt#44]
Part of the mission of Blixt is to have fun with new and burgeoning technologies such as BPF.  Therefore we have been taking multiple experimental approaches to our core eBPF data-plane design and will continue to do so moving forward.  As part of that it will be important to show the performance impact that such design changes have on each iteration. To make this easier a built in tool that can automatically measure performance(bandwidth and latency) in some common scenarios would be extremely helpful. 

Initially, this tooling should start by allowing us to measure UDP performance from an external (out of cluster) client and internal pod with a simple command (make target or script).  From there we can continue to add functionality, I like to read more about [Cilium's performance tooling](https://cilium.io/blog/2021/05/11/cni-benchmark/) to get even more inspiration and ideas. :)

**Comment by shaneutt** [comment]
I'm gonna take this one on. I recently added a [udp test server](https://github.com/Kong/blixt/tree/main/tools/udp-test-server) to this project to test `UDPRoutes`, and I have some ideas about how to add some performance facilities to it which we can then record and track the results of.

**Comment by shaneutt** [comment]
Planning on testing with an [iperf3](https://github.com/esnet/iperf) server.

**Comment by shaneutt** [comment]
A good chunk of this was completed by #72, but the final wiring still needs to be completed once we have https://github.com/Kong/blixt/issues/15 so I added an item to the acceptance criteria there to get the performance test suite plugged in once we have TCP support completed.
