### ISSUE TITLE
Multiple grpc client endpoint management

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/blixt#46]
## Problem Statement

For #41 we added a GRPC client in the controlplane which could connect to and configure the dataplane, but it requires to you create and manage a separate client for every dataplane endpoint (e.g. `Node`) that comes up. The purpose of this task is to create a higher level client that's capable of managing multiple dataplane connections and concurrently shipping new configuration to them all.

## Prerequisites

- [x] #41 

## Acceptance Criteria

- [ ] a single client object can be created which manages multiple dataplane endpoints (when present)
- [ ] the multi-endpoint client is capable of automatically adding new connections when new `Nodes` are added, and old `Nodes` are removed

**Comment by levikobi** [comment]
Hi @shaneutt!
I would like to try taking on this one if that's ok 🙂

Just to make sure I got your intention right, this is my understanding of what should be done here:
1. Currently NewDataPlaneClient returns a BackendsClient, which connects to only one data-plane node. We need a higher-level object which watches for data-plane nodes and keeps an open gRPC connection with each of them (and closes them when the node is gone).
I guess I can implement the watch mechanism the same as you did at the SetupWithManager function?
2. The higher-level object should implement the update & delete operations, in a way that matches the update/delete request to the right data-plane node.
I’m not quite sure yet what is the logic of matching the target to the right data plane node though…
(my guess is we need to match it to the data plane nodes based on the route’s hostIP?)

**Comment by shaneutt** [comment]
> Currently NewDataPlaneClient returns a BackendsClient, which connects to only one data-plane node. We need a higher-level object which watches for data-plane nodes and keeps an open gRPC connection with each of them (and closes them when the node is gone).

Yes, though I did just realize `good first issue` was a misnomer here. This is a little more complex than is fair for a first issue, so I removed that label (but you are still more than welcome to jump in here if this is what interests you). :face_with_spiral_eyes: 

>  I guess I can implement the watch mechanism the same as you did at the SetupWithManager function?
> The higher-level object should implement the update & delete operations, in a way that matches the update/delete request to the right data-plane node. I’m not quite sure yet what is the logic of matching the target to the right data plane node though… (my guess is we need to match it to the data plane nodes based on the route’s hostIP?)

Similarly yes. What I had in mind was basically:

1. a watch which updates the `BackendsClient` with any new `Pods` that belong to the `DaemonSet`, in a threadsafe manner.
2. a channel watch from the `BackendsClient` on the `TCPRoute` and `UDPRoute` controllers which triggers reconciliation after an update to the client's backends, to ensure the configuration gets pushed to the new `Pods`.
3. a client which for the first iteration can just blanket apply configuration changes to all nodes

This approach is reasonably simple, but also inefficient in multiple ways. I think it's important to point out that it's _knowingly_ inefficient: originally in this project we actually had each dataplane `Pod` include a controller and so the dataplane configuration was distributed according to a _pull mechanism_ rather than a push. We knowingly chose the gRPC architecture because it made testing and debugging significantly easier and that's still helpful at these early stages of the project. Suffice to say: in the future we will potentially go back to the pull mechanism, so just keep that in mind if you decide you want to work on this and perhaps only go for minimum viable.

Let me know if that's helpful, if I can continue to be of any help, and if you have any questions? And thank you for your interest in this project! :partying_face:

**Comment by levikobi** [comment]
Got it. Thanks for the explanation! It definitely helped me to get a better understanding of what's going on.

I'll do it :)

**Comment by shaneutt** [comment]
Awesome, thanks and let us know if you run into any trouble or need any support moving it forward, the best place for now is probably the `#ebpf` channel on Kubernetes slack :vulcan_salute:

**Comment by shaneutt** [comment]
Oh, and also please check out https://github.com/Kong/blixt/discussions/42

I think you already know this because of your activity with Gateway API, but this is being donated to Gateway API once the CNCF is able to move forward on licensing votes. During this time, contributors will be asked to sign both the Kong CLA AND the CNCF CLA for contributions. Kinda annoying to have to do multiple CLAs, but it's just an interim thing let us know if this will be any trouble for you.

**Comment by astoycos** [comment]
Thanks so much for sticking with it @levikobi!
