### ISSUE TITLE
Dataplane interface resolution with syscalls

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/blixt#49]
## Problem Statement

During #41 we added a mechanism to identify the [kind-net](https://kind.sigs.k8s.io/) network interface that would be needed for our TC program to redirect packets to `Pods`, but as a stop-gap as the PR was already getting quite large we implemented that using the `iproute2` command line. The purpose of this task is to replace that with syscalls to make it more portable.

## Prerequisites

- [x] #41 

## Additional Notes

Investigate ~https://github.com/redhat-et/emerita/blob/ade6ca9c1215704da6ce033e0b4e8a5f39dbd908/emerita/src/netlink.rs#L46~ https://github.com/rust-netlink

Check out this crate, which is higher level and doesn't require direct syscalls: https://crates.io/crates/netlink-packet-route

## Acceptance Criteria

- [ ] `iproute2` should no longer be required in order for the dataplane to work

**Comment by rushi47** [comment]
Not sure @shaneutt if I could pull this off. But would love to know if this one, is good point to jump & look towards Data-plane

**Comment by shaneutt** [comment]
> Not sure @shaneutt if I could pull this off. But would love to know if this one, is good point to jump & look towards Data-plane

Yeah, I would say so. I think though it is fair to say, that while it's _in_ the dataplane code the subject matter is more of Rust and Linux than of the data path (e.g. this doesn't require any eBPF code changes).

**Comment by rushi47** [comment]
Can I give shot to this 🤚

**Comment by rushi47** [comment]
@shaneutt Oh perfect, will you be able to assign me this then ?
Will take this one first.

**Comment by shaneutt** [comment]
One thing I noticed about https://crates.io/crates/netlink-packet-route (which RedHat is using) is that it appears to be archived: https://github.com/little-dude/netlink

:thinking: @astoycos were you all at RedHat aware of this? Have there been any considerations to fork and continue maintenance?

**Comment by shaneutt** [comment]
Just a heads up, looks like a couple of months ago the Netlink crate's source moved to:

https://github.com/rust-netlink

Looks like things aren't fully moved over yet, including the crates.io page not updated yet. Just a heads up.
