### ISSUE TITLE
mTLS for dataplane API

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/blixt#50]
## Problem Statement

We want to have [mutual TLS authentication](https://grpc.io/docs/guides/auth/) for the dataplane GRPC API.

## Acceptance Criteria

-  [ ] mTLS is automatically configured for encrypting _and authenticating_ controlplane to dataplane communications

**Comment by Rahul-D78** [comment]
can I work on this one please

**Comment by shaneutt** [comment]
> can I work on this one please

Yes, thank you @Rahul-D78! :clinking_glasses:

**Comment by shaneutt** [comment]
Heya @Rahul-D78 :wave: 

We haven't heard back from you in some time, just wanted to check in: are you still working on this and/or interested in working on this?

**Comment by shaneutt** [comment]
@Rahul-D78 since we haven't heard back from you, we're going to unassign you for now in case someone else wants to give this a try. Please do let us know if you're still interested though!

**Comment by rushi47** [comment]
@shaneutt  Can i give a shot ? 👀  to this one

**Comment by shaneutt** [comment]
Sounds good, thank you @rushi47!

**Comment by EandrewJones** [comment]
Mind if I pick this up? Looks like we can easily add tls to tonic by switching on the "tls" feature flag.

**Comment by shaneutt** [comment]
Sounds good, thanks! Let us know how we can support you.

/assign @EandrewJones

**Comment by EandrewJones** [comment]
I won't be shy.

**Comment by shaneutt** [comment]
@EandrewJones are you still interested in this one?

**Comment by EandrewJones** [comment]
Yes, I have some code for it but need to write a test. I also thought y'all
deprioritised this ticket on our last call. So I've let it slip.

All my extracurriculars have been on hold this summer, until I finish my
move next week. Will try to push something early September.

**Comment by shaneutt** [comment]
No worries I was just checking in because I was scanning over the current milestones, no rush just wanted to make sure you still wanted this (before I like, unassigned it and put it back in the pile or something) :+1:
