### ISSUE TITLE
Dockerfile with release builds

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/blixt#6]
For early builds we just used `archlinux` and a debug build of the dataplane components in `dataplane/Dockerfile` as this was fine for early testing. The purpose of this task is to harden this:

- [ ] switch to a different base, perhaps `alpine` with a `musl` libc build
- [ ] enable release builds for images by default
- [ ] (optionally) add debug builds as a special tag

**Comment by shaneutt** [comment]
@LCaparelli just wanted to check back in on this one?

**Comment by vucong2409** [comment]
Hi, I'm a newcomer and interested in working with this issue. However, I just checked and saw that `dataplane/Dockerfile` already switched to `alpine` image. So is issue this still open?

**Comment by shaneutt** [comment]
Thanks for checking in! Yes, our bad this one was already resolved as a side-effect of https://github.com/kubernetes-sigs/blixt/commit/f61d9ad74edeca9661f155992837ff71724ad865.

However if you're interested in anything else let us know how we can help, and be sure to check in with us in `#blixt` on Kubernetes slack :vulcan_salute:
