### ISSUE TITLE
TCP and UDP performance tests

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/blixt#87]
The purpose of this task is to finish the performance test suite we started in #44 and hook it up so that regular performance tests are being run and collected for both `TCPRoute` and `UDPRoute` using `iperf3`.

**Comment by placehldr** [comment]
Hey, @shaneutt are you accepting contributions for Blixt rn or waiting for the migration? If yes, would love to contribute wherever, starting with this

**Comment by shaneutt** [comment]
We're happy to take contributions prior to the migration! There are a couple caveats:

- until the migration is complete, the authors of contributions must have signed the CNCF CLA and provided some link to show for it. See https://github.com/kong/blixt/discussions/42 for more details.
- we may not want to accept any contributions to the `dataplane/` directory specifically (I don't think that will be needed for this work) as the CNCF has still not provided any clarity on the GPLv2 licensing situation in https://github.com/cncf/foundation/issues/474.

But yes, if you're OK with the CNCF CLA we would definitely appreciate some help with this one. Basically there's a bit of prior art (#44) and it should be a matter of: building on top of our existing [ktf](https://github.com/kong/kubernetes-testing-framework) test suite, firing up some UDP and TCP test services (there are examples of this in `test/integration`) using `perf3` to test them and record the results as test artifacts in Github Actions.

A note: the testing environment currently only runs on Linux, this is because KTF [doesn't fully support Mac OS at the moment](https://github.com/Kong/kubernetes-testing-framework/issues/29). So just note that you'll need a Linux machine to do this on OR if you want to help with the Mac environment problem first that would be good too.

**Comment by shaneutt** [comment]
The migration is complete, so it's just the CNCF CLA from here :vulcan_salute:

**Comment by shaneutt** [comment]
We recently decided to rewrite the control-plane in Rust (see https://github.com/kubernetes-sigs/blixt/milestone/8) so for the moment, this issue is out-of-date and we'll close it to avoid confusion.
